import { Slider } from 'antd';
export declare const SchemaField: {
    <Decorator extends import("@formily/react").JSXComponent, Component extends import("@formily/react").JSXComponent>(props: import("@formily/react").ISchemaFieldProps<Decorator, Component, import("@formily/core").ObjectField<Decorator, Component>>): JSX.Element;
    displayName: string;
    Markup: {
        <Decorator_1 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_1 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaMarkupFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_1, Decorator_1>): JSX.Element;
        displayName: string;
    };
    String: {
        <Decorator_2 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_2 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_2, Decorator_2>): JSX.Element;
        displayName: string;
    };
    Object: {
        <Decorator_3 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_3 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_3, Decorator_3>): JSX.Element;
        displayName: string;
    };
    Array: {
        <Decorator_4 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_4 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_4, Decorator_4>): JSX.Element;
        displayName: string;
    };
    Boolean: {
        <Decorator_5 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_5 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_5, Decorator_5>): JSX.Element;
        displayName: string;
    };
    Date: {
        <Decorator_6 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_6 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_6, Decorator_6>): JSX.Element;
        displayName: string;
    };
    DateTime: {
        <Decorator_7 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_7 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_7, Decorator_7>): JSX.Element;
        displayName: string;
    };
    Void: {
        <Decorator_8 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_8 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_8, Decorator_8>): JSX.Element;
        displayName: string;
    };
    Number: {
        <Decorator_9 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`, Component_9 extends "Space" | "FormItem" | "CollapseItem" | "Input" | "ValueInput" | "SizeInput" | "ColorInput" | "ImageInput" | "MonacoInput" | "PositionInput" | "CornerInput" | "BackgroundImageInput" | "BackgroundStyleSetter" | "BoxStyleSetter" | "BorderStyleSetter" | "BorderRadiusStyleSetter" | "DisplayStyleSetter" | "BoxShadowStyleSetter" | "FlexStyleSetter" | "FontStyleSetter" | "DrawerSetter" | "NumberPicker" | "DatePicker" | "TimePicker" | "Select" | "Radio" | "Slider" | "Switch" | "ArrayItems" | "ArrayTable" | "FormCollapse" | "FormGrid" | "FormLayout" | "FormTab" | `Space.${string}` | `FormItem.${string}` | `Input.${string}` | "MonacoInput.loader" | `NumberPicker.${string}` | `DatePicker.${string}` | `TimePicker.${string}` | `Select.${string}` | `Radio.${string}` | "Slider.contextType" | "Slider.prototype" | `Switch.${string}` | `ArrayItems.${string}` | `ArrayTable.${string}` | `FormCollapse.${string}` | `FormGrid.${string}` | `FormLayout.${string}` | `FormTab.${string}`>(props: import("@formily/react").ISchemaTypeFieldProps<{
            FormItem: any;
            CollapseItem: import("react").FC<import("./components").ICollapseItemProps>;
            Input: any;
            ValueInput: import("react").FC<import("./components").IInput>;
            SizeInput: import("react").FC<import("./components").IInput>;
            ColorInput: import("react").FC<import("./components").IColorInputProps>;
            ImageInput: import("react").FC<import("./components").ImageInputProps>;
            MonacoInput: import("react").FC<import("./components").MonacoInputProps> & {
                loader?: typeof import("@monaco-editor/react").loader;
            };
            PositionInput: import("react").FC<import("./components").IPositionInputProps>;
            CornerInput: import("react").FC<import("./components").ICornerInputProps>;
            BackgroundImageInput: import("react").FC<import("./components").ImageInputProps>;
            BackgroundStyleSetter: import("react").FC<import("./components").IBackgroundStyleSetterProps>;
            BoxStyleSetter: import("react").FC<import("./components").IMarginStyleSetterProps>;
            BorderStyleSetter: import("react").FC<import("./components").IBorderStyleSetterProps>;
            BorderRadiusStyleSetter: import("react").FC<import("./components").IBorderRadiusStyleSetterProps>;
            DisplayStyleSetter: import("react").FC<import("./components").IDisplayStyleSetterProps>;
            BoxShadowStyleSetter: import("react").FC<import("./components").IBoxShadowStyleSetterProps>;
            FlexStyleSetter: import("react").FC<import("./components").IFlexStyleSetterProps>;
            FontStyleSetter: import("react").FC<import("./components").IFontStyleSetterProps>;
            DrawerSetter: import("react").FC<import("./components").IDrawerSetterProps>;
            NumberPicker: any;
            DatePicker: any;
            TimePicker: any;
            Select: any;
            Radio: any;
            Slider: typeof Slider;
            Switch: any;
            Space: any;
            ArrayItems: any;
            ArrayTable: any;
            FormCollapse: any;
            FormGrid: any;
            FormLayout: any;
            FormTab: any;
        }, Component_9, Decorator_9>): JSX.Element;
        displayName: string;
    };
};
